cart/urls.py
from django.urls import path
from .views import HomeView, ProductDetailView, CartDeteailView, delete_from_cart, category

app_name = 'cart'


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('product/<int:product_id>/', ProductDetailView.as_view(), name='detail'),
    path('delete/<int:product_id>/', delete_from_cart, name='delete'),
    path('cart-detail/', CartDeteailView.as_view(), name='cart_detail'),
    path('category/<int:id>/', category, name='category'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cart.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    
class Products(models.Model):
    name = models.CharField(max_length=100)
    price = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    description = models.TextField()
    image = models.ImageField(upload_to='product_image', null=True)
    in_stock = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products', null=True)

    def __str__(self):
        return self.name
    
    @property
    def total_price(self):
        return self.price * self.quantity
    

class Cart(models.Model):
    product = models.OneToOneField(Products, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()


    def __str__(self):
        return self.product.name
    

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from .models import Products, Cart, Category


class HomeView(View):
    def get(self, request):
        products = Products.objects.filter(in_stock=True)
        cart = Cart.objects.count()
        return render(request, 'cart/home.html', context={"products":products, "cart":cart})

class ProductDetailView(View):
    def get(self, request, product_id):
        product = get_object_or_404(Products, id=product_id)
        cart = Cart.objects.count()
        return render(request, 'cart/detail.html', context={"product":product, "cart":cart})
    

    def post(self, request, product_id):
        product = get_object_or_404(Products, id=product_id)
        quantity = int(request.POST['cart'])
        if Cart.objects.filter(product=product).exists():
            cart = Cart.objects.filter(product=product).first()
            cart.quantity += quantity
            cart.save()
        else:
            cart = Cart()
            cart.product = product
            cart.quantity = quantity
            cart.save()
        return redirect('cart:home')
    
class CartDeteailView(View):
    def get(self, request):
        products = Cart.objects.all()
        return render(request, 'cart/cart_detail.html', context={"products":products})
    

def delete_from_cart(request, product_id):
    cart = get_object_or_404(Cart, id=product_id)
    cart.delete()
    return redirect('cart:home')


def category(request, id):
    cat = get_object_or_404(Category, id=id)
    products = cat.products.all()
    categories = Category.objects.all()
    return render(request, 'home.html', context={"products":products, "categories":categories})

cart/templates/cart/cart_detail.html
{% extends 'base.html' %}

{% block content %}

<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {% for cart in products %}
            <div class="col mb-5">
                <div class="card h-100">
                    <!-- Product image-->
                    <img class="card-img-top" src="{{cart.product.image.url}}" alt="..." />
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">{{cart.product.name}}</h5>
                            <!-- Product price-->
                            Quantity: {{cart.quantity}}
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-danger mt-auto" href="{% url 'cart:delete' cart.id %}">Remove from cart</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

{% endblock content %}

cart/templates/cart/detail.html
{% extends 'base.html' %}

{% block content %}

<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="{{product.image.url}}" alt="..." /></div>
            <div class="col-md-6">
                <div class="small mb-1">SKU: BST-498</div>
                <h1 class="display-5 fw-bolder">{{product.name}}</h1>
                <div class="fs-5 mb-5">
                    
                    <span>${{product.price}}</span>
                </div>
                <p class="lead">{{product.description}}</p>
                <div class="d-flex">
                    <form action="" method="post">
                        {% csrf_token %}
                        <input class="form-control text-center me-3" id="inputQuantity" name="cart" type="num" value="1" style="max-width: 3rem" />
                        <button class="btn btn-outline-dark flex-shrink-0" type="submit">
                        <i class="bi-cart-fill me-1"></i>
                        Add to cart
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

cart/templates/cart/home.html
{% extends 'base.html' %}

{% block content %}

<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {% for product in products %}
            <div class="col mb-5">
                <div class="card h-100">
                    <!-- Product image-->
                    <img class="card-img-top" src="{{product.image.url}}" alt="..." />
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">{{product.name}}</h5>
                            <!-- Product price-->
                            ${{product.price}}
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'cart:detail' product.id %}">Batafsil</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Shop Homepage - Start Bootstrap Template</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet" />
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.3.1/mdb.min.css" rel="stylesheet" />
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="#!">Start Bootstrap</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Category</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% for cat in cat %}
                                <li><a class="dropdown-item" href="{% url 'cart:category' cat.id %}">{{cat.name}}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                </ul>
                <form class="d-flex">
                    <a class="btn btn-outline-dark" href="{% url 'cart:cart_detail' %}">
                        <i class="bi-cart-fill me-1"></i>
                        Cart
                        <span class="badge bg-dark text-white ms-1 rounded-pill">{{cart}}</span>
                    </a>
                </form>
            </div>
        </div>
    </nav>


    {% block content %}

    {% endblock content %}

    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js' %}"></script>
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.3.1/mdb.umd.min.js"></script>

</body>

</html>